In [1]:
import numpy as np
from os import chdir; chdir('../')
from lib.helpers.database_helper import connect_to_postgres
conn, cur = connect_to_postgres()

In [2]:
cur.execute("SELECT ppl_char_1,ppl_char_2 FROM people LIMIT 10")
this_row = cur.fetchone()
print(this_row)
one_hot = []
while this_row:
    one_hot.append([
            this_row[0] == 'type 01',
            this_row[0] == 'type 02',
            this_row[1] == 'type 01',
            this_row[1] == 'type 02',
            this_row[1] == 'type 03',
        ])
    this_row = cur.fetchone()
print(np.array(one_hot, dtype=int))

('type 02', 'type 02')
[[0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]]
