In [2]:
import psycopg2
import numpy as np
from os import environ
conn = psycopg2.connect(dbname='postgres', user='postgres', host=environ['POSTGRES_1_PORT_5432_TCP_ADDR'])
cur = conn.cursor()

In [3]:
cur.execute("SELECT ppl_char_1,ppl_char_2 FROM people LIMIT 10")
this_row = cur.fetchone()
print(this_row)
one_hot = []
while this_row:
    one_hot.append([
            this_row[0] == 'type 01',
            this_row[0] == 'type 02',
            this_row[1] == 'type 01',
            this_row[1] == 'type 02',
            this_row[1] == 'type 03',
        ])
    this_row = cur.fetchone()
print(np.array(one_hot, dtype=int))

('type 02', 'type 02')
[[0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]]


In [4]:
eye_3 = np.eye(3)

In [20]:
conn = psycopg2.connect(dbname='postgres', user='postgres', host=environ['POSTGRES_1_PORT_5432_TCP_ADDR'])
cur = conn.cursor()
cur.execute("SELECT act_id FROM action LIMIT 1")
action_id = cur.fetchone()[0]
sql = """
UPDATE action 
SET act_one_hot_encoding = {}
WHERE act_id='{}'
""".format(psycopg2.Binary(eye_3), action_id)
cur.execute(sql)
conn.commit()

In [25]:
cur.execute("""
SELECT act_one_hot_encoding 
FROM action 
WHERE act_id='{}'
""".format(action_id))
buf = cur.fetchone()[0]
np.frombuffer(buf)

array([ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.])