In [1]:
from numpy import array
from os import chdir; chdir('../')
from lib.helpers.database_helper import connect_to_postgres
conn, cur = connect_to_postgres()

In [2]:
col_1 = 'ppl_char_1' # e.g. ppl_char_1, ..., ppl_char_39
col_2 = 'ppl_char_2' 

In [3]:
cur.execute("SELECT {}, {} FROM people LIMIT 10".format(col_1, col_2))
this_row = cur.fetchone()
attr_1 = [this_row[0]]
attr_2 = [this_row[1]]
while this_row:
    attr_1.append(this_row[0])
    attr_2.append(this_row[1])
    this_row = cur.fetchone()

In [4]:
one_hot = []
for this_at_1, this_at_2 in zip(attr_1, attr_2):
    one_hot_at_1 = [this_at_1 == set_at_1 for set_at_1 in set(attr_1)]
    one_hot_at_2 = [this_at_2 == set_at_2 for set_at_2 in set(attr_2)]
    this_one_hot = one_hot_at_1 + one_hot_at_2
    one_hot.append(this_one_hot)
print(array(one_hot, dtype=int))

[[1 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [1 1 0]]
