In [1]:
import numpy as np

In [2]:
import numpy.random as ne

In [82]:
ne.randn(2,100)

array([[ 0.77797683,  0.82074164,  0.66930336, -1.37971502,  1.03120443,
         1.45678102,  1.20243539,  2.07151824,  0.15936917, -0.51297835,
         1.82383418, -1.62017293, -0.44552955, -1.01540025,  0.06613209,
         0.19572655, -1.84710263, -1.02451507,  0.17839654,  1.75498714,
        -1.85318738, -0.48214294, -1.57998632,  0.30680124,  0.17271787,
        -0.10536166, -1.96062574,  0.4291534 , -0.2063494 , -0.39698179,
         0.76331964,  0.40431574, -1.2745023 ,  0.48226049, -0.61764349,
         0.91728912,  1.01811394, -0.8010712 ,  0.32864679,  0.14776598,
         0.16624955,  1.27665808, -1.12829496, -0.23049573, -1.09608298,
        -0.52041822,  1.40172718, -0.78804145, -1.79111375,  0.51683648,
         0.13326264,  1.62932141, -0.27359434, -0.68372164, -0.28733829,
         0.02807111,  2.3127778 , -0.70623078,  0.74095276,  0.74149958,
         1.46569616, -0.96478859, -0.72236667,  2.15563048, -0.11585193,
        -0.49107119, -0.17480944,  0.30961983, -1.5

In [191]:
foo = np.greater(np.zeros(3),ne.randn(3)-.5).astype(int)

In [192]:
foo

array([1, 0, 1])

In [193]:
foo -1

array([ 0, -1,  0])

In [194]:
np.abs(foo-1)

array([0, 1, 0])

In [195]:
abs(foo-1)

array([0, 1, 0])

In [196]:
scores = ne.random((3,2))

In [197]:
scores

array([[ 0.4570255 ,  0.75911605],
       [ 0.02832772,  0.42227377],
       [ 0.08182912,  0.53962359]])

In [198]:
scores[np.arange(len(foo)), foo] = 0
scores[np.arange(len(foo)), foo] = - np.sum(scores,axis=1)

In [210]:
scores.T[0]

array([ 0.4570255 , -0.42227377,  0.08182912])

In [214]:
x+10

array([[ 11.9069035 ,  11.45901241,   8.27848562],
       [  8.44882384,  10.37237379,  10.64242298],
       [ 11.80564127,  10.28597876,   9.43692923],
       [ 10.669112  ,  10.61990538,  10.13865446],
       [  7.45022773,  10.97805487,   7.76657418],
       [ 10.71961456,   9.00169107,   9.3168201 ],
       [ 11.68007865,  10.03949622,   9.48794609],
       [  9.64191556,  10.35282199,   9.73172615],
       [ 10.01608366,  11.00949655,   9.63735427],
       [ 10.20623648,   9.73630682,  11.00073097]])

In [213]:
x = ne.randn(10,3)
x

array([[ 1.9069035 ,  1.45901241, -1.72151438],
       [-1.55117616,  0.37237379,  0.64242298],
       [ 1.80564127,  0.28597876, -0.56307077],
       [ 0.669112  ,  0.61990538,  0.13865446],
       [-2.54977227,  0.97805487, -2.23342582],
       [ 0.71961456, -0.99830893, -0.6831799 ],
       [ 1.68007865,  0.03949622, -0.51205391],
       [-0.35808444,  0.35282199, -0.26827385],
       [ 0.01608366,  1.00949655, -0.36264573],
       [ 0.20623648, -0.26369318,  1.00073097]])

In [202]:
scores.T.dot(x.T)

array([[-0.65243052, -1.19632618,  1.60643081,  1.38717565,  0.41304609,
         0.21845961,  0.14937048, -1.17697368,  1.29640879, -1.02450873],
       [ 0.65243052,  1.19632618, -1.60643081, -1.38717565, -0.41304609,
        -0.21845961, -0.14937048,  1.17697368, -1.29640879,  1.02450873]])

In [75]:
grads_tensor = grads.reshape(int(grads.shape[0]/2), 2, grads.shape[1])

In [79]:
grads_tensor

array([[[ 0.39868385,  0.19167372,  0.52747791,  0.64830039,  0.44478711,
          0.920966  ,  0.83739383,  0.6754045 ,  0.57081234,  0.18150875],
        [-0.39868385, -0.19167372, -0.52747791, -0.64830039, -0.44478711,
         -0.920966  , -0.83739383, -0.6754045 , -0.57081234, -0.18150875]],

       [[-0.4208835 , -0.20234656, -0.55684911, -0.68439927, -0.46955389,
         -0.97224752, -0.88402187, -0.71301259, -0.6025965 , -0.19161558],
        [ 0.4208835 ,  0.20234656,  0.55684911,  0.68439927,  0.46955389,
          0.97224752,  0.88402187,  0.71301259,  0.6025965 ,  0.19161558]]])

In [80]:
sum(grads_tensor)

array([[-0.02219964, -0.01067284, -0.0293712 , -0.03609887, -0.02476678,
        -0.05128153, -0.04662804, -0.03760809, -0.03178416, -0.01010683],
       [ 0.02219964,  0.01067284,  0.0293712 ,  0.03609887,  0.02476678,
         0.05128153,  0.04662804,  0.03760809,  0.03178416,  0.01010683]])

In [58]:
np.broadcast_arrays?


In [48]:
np.dot?